// Generated by scripts/fetch-f1-champion-stats.mjs from the RaceData F1 archive.
export type ChampionSeasonStats = { name: string; wins: number; podiums: number; poles: number; dnfs: number; points: number };
export type ConstructorSeasonStats = { constructorName: string; drivers: ChampionSeasonStats[]; total: Omit<ChampionSeasonStats, "name"> };

export const driverSeasonStats: Record<number, ChampionSeasonStats> = {
  "1950": {
    "name": "Giuseppe Farina",
    "wins": 3,
    "podiums": 3,
    "poles": 2,
    "dnfs": 2,
    "points": 30
  },
  "1951": {
    "name": "Juan Manuel Fangio",
    "wins": 3,
    "podiums": 5,
    "poles": 4,
    "dnfs": 1,
    "points": 31
  },
  "1952": {
    "name": "Alberto Ascari",
    "wins": 6,
    "podiums": 6,
    "poles": 5,
    "dnfs": 1,
    "points": 36
  },
  "1953": {
    "name": "Alberto Ascari",
    "wins": 5,
    "podiums": 5,
    "poles": 6,
    "dnfs": 2,
    "points": 34.5
  },
  "1954": {
    "name": "Juan Manuel Fangio",
    "wins": 6,
    "podiums": 7,
    "poles": 5,
    "dnfs": 0,
    "points": 42
  },
  "1955": {
    "name": "Juan Manuel Fangio",
    "wins": 4,
    "podiums": 5,
    "poles": 3,
    "dnfs": 1,
    "points": 40
  },
  "1956": {
    "name": "Juan Manuel Fangio",
    "wins": 3,
    "podiums": 5,
    "poles": 6,
    "dnfs": 2,
    "points": 30
  },
  "1957": {
    "name": "Juan Manuel Fangio",
    "wins": 4,
    "podiums": 6,
    "poles": 4,
    "dnfs": 1,
    "points": 40
  },
  "1958": {
    "name": "Mike Hawthorn",
    "wins": 1,
    "podiums": 7,
    "poles": 4,
    "dnfs": 2,
    "points": 42
  },
  "1959": {
    "name": "Jack Brabham",
    "wins": 2,
    "podiums": 5,
    "poles": 1,
    "dnfs": 2,
    "points": 31
  },
  "1960": {
    "name": "Jack Brabham",
    "wins": 5,
    "podiums": 5,
    "poles": 3,
    "dnfs": 2,
    "points": 43
  },
  "1961": {
    "name": "Phil Hill",
    "wins": 2,
    "podiums": 6,
    "poles": 5,
    "dnfs": 5,
    "points": 34
  },
  "1962": {
    "name": "Graham Hill",
    "wins": 4,
    "podiums": 9,
    "poles": 1,
    "dnfs": 3,
    "points": 42
  },
  "1963": {
    "name": "Jim Clark",
    "wins": 7,
    "podiums": 9,
    "poles": 7,
    "dnfs": 1,
    "points": 54
  },
  "1964": {
    "name": "John Surtees",
    "wins": 2,
    "podiums": 6,
    "poles": 2,
    "dnfs": 4,
    "points": 40
  },
  "1965": {
    "name": "Jim Clark",
    "wins": 6,
    "podiums": 6,
    "poles": 6,
    "dnfs": 3,
    "points": 54
  },
  "1966": {
    "name": "Jack Brabham",
    "wins": 4,
    "podiums": 5,
    "poles": 3,
    "dnfs": 3,
    "points": 42
  },
  "1967": {
    "name": "Denny Hulme",
    "wins": 2,
    "podiums": 8,
    "poles": 0,
    "dnfs": 2,
    "points": 51
  },
  "1968": {
    "name": "Graham Hill",
    "wins": 3,
    "podiums": 6,
    "poles": 2,
    "dnfs": 5,
    "points": 48
  },
  "1969": {
    "name": "Jackie Stewart",
    "wins": 6,
    "podiums": 7,
    "poles": 2,
    "dnfs": 3,
    "points": 63
  },
  "1970": {
    "name": "Jochen Rindt",
    "wins": 5,
    "podiums": 5,
    "poles": 3,
    "dnfs": 5,
    "points": 45
  },
  "1971": {
    "name": "Jackie Stewart",
    "wins": 6,
    "podiums": 7,
    "poles": 6,
    "dnfs": 2,
    "points": 62
  },
  "1972": {
    "name": "Emerson Fittipaldi",
    "wins": 5,
    "podiums": 8,
    "poles": 3,
    "dnfs": 9,
    "points": 61
  },
  "1973": {
    "name": "Jackie Stewart",
    "wins": 5,
    "podiums": 8,
    "poles": 3,
    "dnfs": 2,
    "points": 71
  },
  "1974": {
    "name": "Emerson Fittipaldi",
    "wins": 3,
    "podiums": 7,
    "poles": 2,
    "dnfs": 3,
    "points": 55
  },
  "1975": {
    "name": "Niki Lauda",
    "wins": 5,
    "podiums": 8,
    "poles": 9,
    "dnfs": 1,
    "points": 64.5
  },
  "1976": {
    "name": "James Hunt",
    "wins": 6,
    "podiums": 8,
    "poles": 8,
    "dnfs": 6,
    "points": 69
  },
  "1977": {
    "name": "Niki Lauda",
    "wins": 3,
    "podiums": 10,
    "poles": 2,
    "dnfs": 3,
    "points": 72
  },
  "1978": {
    "name": "Mario Andretti",
    "wins": 6,
    "podiums": 7,
    "poles": 8,
    "dnfs": 4,
    "points": 64
  },
  "1979": {
    "name": "Jody Scheckter",
    "wins": 3,
    "podiums": 6,
    "poles": 1,
    "dnfs": 2,
    "points": 51
  },
  "1980": {
    "name": "Alan Jones",
    "wins": 5,
    "podiums": 10,
    "poles": 3,
    "dnfs": 3,
    "points": 67
  },
  "1981": {
    "name": "Nelson Piquet",
    "wins": 3,
    "podiums": 7,
    "poles": 4,
    "dnfs": 5,
    "points": 50
  },
  "1982": {
    "name": "Keke Rosberg",
    "wins": 1,
    "podiums": 6,
    "poles": 1,
    "dnfs": 4,
    "points": 44
  },
  "1983": {
    "name": "Nelson Piquet",
    "wins": 3,
    "podiums": 8,
    "poles": 1,
    "dnfs": 5,
    "points": 59
  },
  "1984": {
    "name": "Niki Lauda",
    "wins": 5,
    "podiums": 9,
    "poles": 0,
    "dnfs": 6,
    "points": 72
  },
  "1985": {
    "name": "Alain Prost",
    "wins": 5,
    "podiums": 11,
    "poles": 2,
    "dnfs": 4,
    "points": 73
  },
  "1986": {
    "name": "Alain Prost",
    "wins": 4,
    "podiums": 11,
    "poles": 1,
    "dnfs": 4,
    "points": 72
  },
  "1987": {
    "name": "Nelson Piquet",
    "wins": 3,
    "podiums": 11,
    "poles": 4,
    "dnfs": 4,
    "points": 73
  },
  "1988": {
    "name": "Ayrton Senna",
    "wins": 8,
    "podiums": 11,
    "poles": 13,
    "dnfs": 3,
    "points": 90
  },
  "1989": {
    "name": "Alain Prost",
    "wins": 4,
    "podiums": 11,
    "poles": 2,
    "dnfs": 3,
    "points": 76
  },
  "1990": {
    "name": "Ayrton Senna",
    "wins": 6,
    "podiums": 11,
    "poles": 10,
    "dnfs": 5,
    "points": 78
  },
  "1991": {
    "name": "Ayrton Senna",
    "wins": 7,
    "podiums": 12,
    "poles": 8,
    "dnfs": 3,
    "points": 96
  },
  "1992": {
    "name": "Nigel Mansell",
    "wins": 9,
    "podiums": 12,
    "poles": 14,
    "dnfs": 4,
    "points": 108
  },
  "1993": {
    "name": "Alain Prost",
    "wins": 7,
    "podiums": 12,
    "poles": 13,
    "dnfs": 2,
    "points": 99
  },
  "1994": {
    "name": "Michael Schumacher",
    "wins": 8,
    "podiums": 10,
    "poles": 6,
    "dnfs": 4,
    "points": 92
  },
  "1995": {
    "name": "Michael Schumacher",
    "wins": 9,
    "podiums": 11,
    "poles": 4,
    "dnfs": 5,
    "points": 102
  },
  "1996": {
    "name": "Damon Hill",
    "wins": 8,
    "podiums": 10,
    "poles": 9,
    "dnfs": 4,
    "points": 97
  },
  "1997": {
    "name": "Jacques Villeneuve",
    "wins": 7,
    "podiums": 8,
    "poles": 10,
    "dnfs": 6,
    "points": 81
  },
  "1998": {
    "name": "Mika Häkkinen",
    "wins": 8,
    "podiums": 11,
    "poles": 9,
    "dnfs": 3,
    "points": 100
  },
  "1999": {
    "name": "Mika Häkkinen",
    "wins": 5,
    "podiums": 10,
    "poles": 11,
    "dnfs": 5,
    "points": 76
  },
  "2000": {
    "name": "Michael Schumacher",
    "wins": 9,
    "podiums": 15,
    "poles": 9,
    "dnfs": 12,
    "points": 108
  },
  "2001": {
    "name": "Michael Schumacher",
    "wins": 12,
    "podiums": 19,
    "poles": 12,
    "dnfs": 9,
    "points": 123
  },
  "2002": {
    "name": "Michael Schumacher",
    "wins": 12,
    "podiums": 23,
    "poles": 7,
    "dnfs": 5,
    "points": 144
  },
  "2003": {
    "name": "Michael Schumacher",
    "wins": 8,
    "podiums": 11,
    "poles": 8,
    "dnfs": 3,
    "points": 93
  },
  "2004": {
    "name": "Michael Schumacher",
    "wins": 13,
    "podiums": 16,
    "poles": 9,
    "dnfs": 7,
    "points": 148
  },
  "2005": {
    "name": "Fernando Alonso",
    "wins": 7,
    "podiums": 15,
    "poles": 6,
    "dnfs": 2,
    "points": 133
  },
  "2006": {
    "name": "Fernando Alonso",
    "wins": 7,
    "podiums": 14,
    "poles": 6,
    "dnfs": 2,
    "points": 134
  },
  "2007": {
    "name": "Kimi Räikkönen",
    "wins": 6,
    "podiums": 12,
    "poles": 3,
    "dnfs": 2,
    "points": 110
  },
  "2008": {
    "name": "Lewis Hamilton",
    "wins": 5,
    "podiums": 10,
    "poles": 7,
    "dnfs": 1,
    "points": 98
  },
  "2009": {
    "name": "Jenson Button",
    "wins": 6,
    "podiums": 9,
    "poles": 4,
    "dnfs": 1,
    "points": 95
  },
  "2010": {
    "name": "Sebastian Vettel",
    "wins": 5,
    "podiums": 10,
    "poles": 10,
    "dnfs": 3,
    "points": 256
  },
  "2011": {
    "name": "Sebastian Vettel",
    "wins": 11,
    "podiums": 17,
    "poles": 15,
    "dnfs": 1,
    "points": 392
  },
  "2012": {
    "name": "Sebastian Vettel",
    "wins": 5,
    "podiums": 10,
    "poles": 6,
    "dnfs": 2,
    "points": 281
  },
  "2013": {
    "name": "Sebastian Vettel",
    "wins": 13,
    "podiums": 16,
    "poles": 9,
    "dnfs": 1,
    "points": 397
  },
  "2014": {
    "name": "Lewis Hamilton",
    "wins": 11,
    "podiums": 16,
    "poles": 7,
    "dnfs": 3,
    "points": 384
  },
  "2015": {
    "name": "Lewis Hamilton",
    "wins": 10,
    "podiums": 17,
    "poles": 11,
    "dnfs": 1,
    "points": 381
  },
  "2016": {
    "name": "Nico Rosberg",
    "wins": 9,
    "podiums": 16,
    "poles": 8,
    "dnfs": 1,
    "points": 385
  },
  "2017": {
    "name": "Lewis Hamilton",
    "wins": 9,
    "podiums": 13,
    "poles": 11,
    "dnfs": 0,
    "points": 363
  },
  "2018": {
    "name": "Lewis Hamilton",
    "wins": 11,
    "podiums": 17,
    "poles": 11,
    "dnfs": 1,
    "points": 408
  },
  "2019": {
    "name": "Lewis Hamilton",
    "wins": 11,
    "podiums": 17,
    "poles": 5,
    "dnfs": 0,
    "points": 413
  },
  "2020": {
    "name": "Lewis Hamilton",
    "wins": 11,
    "podiums": 14,
    "poles": 10,
    "dnfs": 0,
    "points": 347
  },
  "2021": {
    "name": "Max Verstappen",
    "wins": 10,
    "podiums": 18,
    "poles": 10,
    "dnfs": 3,
    "points": 395.5
  },
  "2022": {
    "name": "Max Verstappen",
    "wins": 15,
    "podiums": 17,
    "poles": 7,
    "dnfs": 2,
    "points": 454
  },
  "2023": {
    "name": "Max Verstappen",
    "wins": 19,
    "podiums": 21,
    "poles": 12,
    "dnfs": 0,
    "points": 575
  },
  "2024": {
    "name": "Max Verstappen",
    "wins": 9,
    "podiums": 14,
    "poles": 8,
    "dnfs": 1,
    "points": 437
  },
  "2025": {
    "name": "Lando Norris",
    "wins": 7,
    "podiums": 18,
    "poles": 7,
    "dnfs": 3,
    "points": 423
  }
};

export const constructorSeasonStats: Record<number, ConstructorSeasonStats> = {
  "1958": {
    "constructorName": "Vanwall",
    "drivers": [
      {
        "name": "Tony Brooks",
        "wins": 3,
        "podiums": 3,
        "poles": 1,
        "dnfs": 6,
        "points": 24
      },
      {
        "name": "Stirling Moss",
        "wins": 3,
        "podiums": 4,
        "poles": 3,
        "dnfs": 5,
        "points": 24
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 7,
      "poles": 4,
      "dnfs": 11,
      "points": 48
    }
  },
  "1959": {
    "constructorName": "Cooper-Climax",
    "drivers": [
      {
        "name": "Jack Brabham",
        "wins": 2,
        "podiums": 5,
        "poles": 1,
        "dnfs": 2,
        "points": 16
      },
      {
        "name": "Stirling Moss",
        "wins": 2,
        "podiums": 2,
        "poles": 4,
        "dnfs": 4,
        "points": 16
      },
      {
        "name": "Bruce McLaren",
        "wins": 1,
        "podiums": 2,
        "poles": 0,
        "dnfs": 3,
        "points": 8
      }
    ],
    "total": {
      "wins": 5,
      "podiums": 9,
      "poles": 5,
      "dnfs": 9,
      "points": 40
    }
  },
  "1960": {
    "constructorName": "Cooper-Climax",
    "drivers": [
      {
        "name": "Jack Brabham",
        "wins": 5,
        "podiums": 5,
        "poles": 3,
        "dnfs": 2,
        "points": 40
      },
      {
        "name": "Bruce McLaren",
        "wins": 1,
        "podiums": 6,
        "poles": 0,
        "dnfs": 1,
        "points": 8
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 11,
      "poles": 3,
      "dnfs": 3,
      "points": 48
    }
  },
  "1961": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Phil Hill",
        "wins": 2,
        "podiums": 6,
        "poles": 5,
        "dnfs": 0,
        "points": 18
      },
      {
        "name": "Wolfgang von Trips",
        "wins": 2,
        "podiums": 4,
        "poles": 1,
        "dnfs": 3,
        "points": 18
      },
      {
        "name": "Giancarlo Baghetti",
        "wins": 1,
        "podiums": 1,
        "poles": 0,
        "dnfs": 2,
        "points": 9
      }
    ],
    "total": {
      "wins": 5,
      "podiums": 11,
      "poles": 6,
      "dnfs": 5,
      "points": 45
    }
  },
  "1962": {
    "constructorName": "BRM",
    "drivers": [
      {
        "name": "Graham Hill",
        "wins": 4,
        "podiums": 6,
        "poles": 1,
        "dnfs": 1,
        "points": 42
      }
    ],
    "total": {
      "wins": 4,
      "podiums": 6,
      "poles": 1,
      "dnfs": 1,
      "points": 42
    }
  },
  "1963": {
    "constructorName": "Lotus-Climax",
    "drivers": [
      {
        "name": "Jim Clark",
        "wins": 7,
        "podiums": 9,
        "poles": 7,
        "dnfs": 1,
        "points": 54
      }
    ],
    "total": {
      "wins": 7,
      "podiums": 9,
      "poles": 7,
      "dnfs": 1,
      "points": 54
    }
  },
  "1964": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "John Surtees",
        "wins": 2,
        "podiums": 6,
        "poles": 2,
        "dnfs": 4,
        "points": 36
      },
      {
        "name": "Lorenzo Bandini",
        "wins": 1,
        "podiums": 4,
        "poles": 0,
        "dnfs": 4,
        "points": 9
      }
    ],
    "total": {
      "wins": 3,
      "podiums": 10,
      "poles": 2,
      "dnfs": 8,
      "points": 45
    }
  },
  "1965": {
    "constructorName": "Lotus-Climax",
    "drivers": [
      {
        "name": "Jim Clark",
        "wins": 6,
        "podiums": 6,
        "poles": 6,
        "dnfs": 3,
        "points": 54
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 6,
      "poles": 6,
      "dnfs": 3,
      "points": 54
    }
  },
  "1966": {
    "constructorName": "Brabham-Repco",
    "drivers": [
      {
        "name": "Jack Brabham",
        "wins": 4,
        "podiums": 5,
        "poles": 3,
        "dnfs": 3,
        "points": 42
      }
    ],
    "total": {
      "wins": 4,
      "podiums": 5,
      "poles": 3,
      "dnfs": 3,
      "points": 42
    }
  },
  "1967": {
    "constructorName": "Brabham-Repco",
    "drivers": [
      {
        "name": "Jack Brabham",
        "wins": 2,
        "podiums": 6,
        "poles": 2,
        "dnfs": 2,
        "points": 36
      },
      {
        "name": "Denny Hulme",
        "wins": 2,
        "podiums": 8,
        "poles": 0,
        "dnfs": 2,
        "points": 27
      }
    ],
    "total": {
      "wins": 4,
      "podiums": 14,
      "poles": 2,
      "dnfs": 4,
      "points": 63
    }
  },
  "1968": {
    "constructorName": "Lotus-Ford/Cosworth",
    "drivers": [
      {
        "name": "Graham Hill",
        "wins": 3,
        "podiums": 6,
        "poles": 2,
        "dnfs": 5,
        "points": 42
      },
      {
        "name": "Jo Siffert",
        "wins": 1,
        "podiums": 1,
        "poles": 1,
        "dnfs": 7,
        "points": 9
      },
      {
        "name": "Jim Clark",
        "wins": 1,
        "podiums": 1,
        "poles": 1,
        "dnfs": 0,
        "points": 9
      },
      {
        "name": "Jackie Oliver",
        "wins": 0,
        "podiums": 1,
        "poles": 0,
        "dnfs": 7,
        "points": 2
      }
    ],
    "total": {
      "wins": 5,
      "podiums": 9,
      "poles": 4,
      "dnfs": 19,
      "points": 62
    }
  },
  "1969": {
    "constructorName": "Matra-Ford/Cosworth",
    "drivers": [
      {
        "name": "Jackie Stewart",
        "wins": 6,
        "podiums": 7,
        "poles": 2,
        "dnfs": 3,
        "points": 63
      },
      {
        "name": "Jean-Pierre Beltoise",
        "wins": 0,
        "podiums": 3,
        "poles": 0,
        "dnfs": 3,
        "points": 3
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 10,
      "poles": 2,
      "dnfs": 6,
      "points": 66
    }
  },
  "1970": {
    "constructorName": "Lotus-Ford/Cosworth",
    "drivers": [
      {
        "name": "Jochen Rindt",
        "wins": 5,
        "podiums": 5,
        "poles": 3,
        "dnfs": 5,
        "points": 45
      },
      {
        "name": "Emerson Fittipaldi",
        "wins": 1,
        "podiums": 1,
        "poles": 0,
        "dnfs": 2,
        "points": 9
      },
      {
        "name": "Graham Hill",
        "wins": 0,
        "podiums": 0,
        "poles": 0,
        "dnfs": 7,
        "points": 3
      },
      {
        "name": "John Miles",
        "wins": 0,
        "podiums": 0,
        "poles": 0,
        "dnfs": 7,
        "points": 2
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 6,
      "poles": 3,
      "dnfs": 21,
      "points": 59
    }
  },
  "1971": {
    "constructorName": "Tyrrell-Ford/Cosworth",
    "drivers": [
      {
        "name": "Jackie Stewart",
        "wins": 6,
        "podiums": 7,
        "poles": 6,
        "dnfs": 2,
        "points": 60
      },
      {
        "name": "François Cevert",
        "wins": 1,
        "podiums": 4,
        "poles": 0,
        "dnfs": 4,
        "points": 13
      }
    ],
    "total": {
      "wins": 7,
      "podiums": 11,
      "poles": 6,
      "dnfs": 6,
      "points": 73
    }
  },
  "1972": {
    "constructorName": "Lotus-Ford/Cosworth",
    "drivers": [
      {
        "name": "Emerson Fittipaldi",
        "wins": 5,
        "podiums": 8,
        "poles": 3,
        "dnfs": 3,
        "points": 61
      }
    ],
    "total": {
      "wins": 5,
      "podiums": 8,
      "poles": 3,
      "dnfs": 3,
      "points": 61
    }
  },
  "1973": {
    "constructorName": "Lotus-Ford/Cosworth",
    "drivers": [
      {
        "name": "Ronnie Peterson",
        "wins": 4,
        "podiums": 7,
        "poles": 9,
        "dnfs": 7,
        "points": 48
      },
      {
        "name": "Emerson Fittipaldi",
        "wins": 3,
        "podiums": 8,
        "poles": 1,
        "dnfs": 5,
        "points": 44
      }
    ],
    "total": {
      "wins": 7,
      "podiums": 15,
      "poles": 10,
      "dnfs": 12,
      "points": 92
    }
  },
  "1974": {
    "constructorName": "McLaren-Ford/Cosworth",
    "drivers": [
      {
        "name": "Emerson Fittipaldi",
        "wins": 3,
        "podiums": 7,
        "poles": 2,
        "dnfs": 3,
        "points": 54
      },
      {
        "name": "Denny Hulme",
        "wins": 1,
        "podiums": 2,
        "poles": 0,
        "dnfs": 5,
        "points": 15
      },
      {
        "name": "Mike Hailwood",
        "wins": 0,
        "podiums": 1,
        "poles": 0,
        "dnfs": 4,
        "points": 4
      }
    ],
    "total": {
      "wins": 4,
      "podiums": 10,
      "poles": 2,
      "dnfs": 12,
      "points": 73
    }
  },
  "1975": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Niki Lauda",
        "wins": 5,
        "podiums": 8,
        "poles": 9,
        "dnfs": 1,
        "points": 57.5
      },
      {
        "name": "Clay Regazzoni",
        "wins": 1,
        "podiums": 3,
        "poles": 0,
        "dnfs": 6,
        "points": 15
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 11,
      "poles": 9,
      "dnfs": 7,
      "points": 72.5
    }
  },
  "1976": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Niki Lauda",
        "wins": 5,
        "podiums": 9,
        "poles": 3,
        "dnfs": 3,
        "points": 59
      },
      {
        "name": "Clay Regazzoni",
        "wins": 1,
        "podiums": 4,
        "poles": 1,
        "dnfs": 4,
        "points": 24
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 13,
      "poles": 4,
      "dnfs": 7,
      "points": 83
    }
  },
  "1977": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Niki Lauda",
        "wins": 3,
        "podiums": 10,
        "poles": 2,
        "dnfs": 3,
        "points": 66
      },
      {
        "name": "Carlos Reutemann",
        "wins": 1,
        "podiums": 6,
        "poles": 0,
        "dnfs": 4,
        "points": 29
      }
    ],
    "total": {
      "wins": 4,
      "podiums": 16,
      "poles": 2,
      "dnfs": 7,
      "points": 95
    }
  },
  "1978": {
    "constructorName": "Lotus-Ford/Cosworth",
    "drivers": [
      {
        "name": "Mario Andretti",
        "wins": 6,
        "podiums": 7,
        "poles": 8,
        "dnfs": 4,
        "points": 64
      },
      {
        "name": "Ronnie Peterson",
        "wins": 2,
        "podiums": 7,
        "poles": 3,
        "dnfs": 5,
        "points": 22
      }
    ],
    "total": {
      "wins": 8,
      "podiums": 14,
      "poles": 11,
      "dnfs": 9,
      "points": 86
    }
  },
  "1979": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Jody Scheckter",
        "wins": 3,
        "podiums": 6,
        "poles": 1,
        "dnfs": 2,
        "points": 60
      },
      {
        "name": "Gilles Villeneuve",
        "wins": 3,
        "podiums": 7,
        "poles": 1,
        "dnfs": 4,
        "points": 53
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 13,
      "poles": 2,
      "dnfs": 6,
      "points": 113
    }
  },
  "1980": {
    "constructorName": "Williams-Ford/Cosworth",
    "drivers": [
      {
        "name": "Alan Jones",
        "wins": 5,
        "podiums": 10,
        "poles": 3,
        "dnfs": 3,
        "points": 71
      },
      {
        "name": "Carlos Reutemann",
        "wins": 1,
        "podiums": 8,
        "poles": 0,
        "dnfs": 3,
        "points": 49
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 18,
      "poles": 3,
      "dnfs": 6,
      "points": 120
    }
  },
  "1981": {
    "constructorName": "Williams-Ford/Cosworth",
    "drivers": [
      {
        "name": "Carlos Reutemann",
        "wins": 2,
        "podiums": 7,
        "poles": 2,
        "dnfs": 3,
        "points": 49
      },
      {
        "name": "Alan Jones",
        "wins": 2,
        "podiums": 6,
        "poles": 0,
        "dnfs": 4,
        "points": 46
      }
    ],
    "total": {
      "wins": 4,
      "podiums": 13,
      "poles": 2,
      "dnfs": 7,
      "points": 95
    }
  },
  "1982": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Didier Pironi",
        "wins": 2,
        "podiums": 6,
        "poles": 2,
        "dnfs": 4,
        "points": 39
      },
      {
        "name": "Patrick Tambay",
        "wins": 1,
        "podiums": 3,
        "poles": 0,
        "dnfs": 2,
        "points": 25
      },
      {
        "name": "Gilles Villeneuve",
        "wins": 0,
        "podiums": 1,
        "poles": 0,
        "dnfs": 4,
        "points": 6
      },
      {
        "name": "Mario Andretti",
        "wins": 0,
        "podiums": 1,
        "poles": 1,
        "dnfs": 1,
        "points": 4
      }
    ],
    "total": {
      "wins": 3,
      "podiums": 11,
      "poles": 3,
      "dnfs": 11,
      "points": 74
    }
  },
  "1983": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "René Arnoux",
        "wins": 3,
        "podiums": 7,
        "poles": 4,
        "dnfs": 4,
        "points": 49
      },
      {
        "name": "Patrick Tambay",
        "wins": 1,
        "podiums": 5,
        "poles": 4,
        "dnfs": 6,
        "points": 40
      }
    ],
    "total": {
      "wins": 4,
      "podiums": 12,
      "poles": 8,
      "dnfs": 10,
      "points": 89
    }
  },
  "1984": {
    "constructorName": "McLaren-TAG/Porsche",
    "drivers": [
      {
        "name": "Niki Lauda",
        "wins": 5,
        "podiums": 9,
        "poles": 0,
        "dnfs": 6,
        "points": 72
      },
      {
        "name": "Alain Prost",
        "wins": 7,
        "podiums": 9,
        "poles": 3,
        "dnfs": 5,
        "points": 71.5
      }
    ],
    "total": {
      "wins": 12,
      "podiums": 18,
      "poles": 3,
      "dnfs": 11,
      "points": 143.5
    }
  },
  "1985": {
    "constructorName": "McLaren-TAG/Porsche",
    "drivers": [
      {
        "name": "Alain Prost",
        "wins": 5,
        "podiums": 11,
        "poles": 2,
        "dnfs": 4,
        "points": 76
      },
      {
        "name": "Niki Lauda",
        "wins": 1,
        "podiums": 1,
        "poles": 0,
        "dnfs": 11,
        "points": 14
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 12,
      "poles": 2,
      "dnfs": 15,
      "points": 90
    }
  },
  "1986": {
    "constructorName": "Williams-Honda",
    "drivers": [
      {
        "name": "Nigel Mansell",
        "wins": 5,
        "podiums": 9,
        "poles": 2,
        "dnfs": 4,
        "points": 72
      },
      {
        "name": "Nelson Piquet",
        "wins": 4,
        "podiums": 10,
        "poles": 2,
        "dnfs": 4,
        "points": 69
      }
    ],
    "total": {
      "wins": 9,
      "podiums": 19,
      "poles": 4,
      "dnfs": 8,
      "points": 141
    }
  },
  "1987": {
    "constructorName": "Williams-Honda",
    "drivers": [
      {
        "name": "Nelson Piquet",
        "wins": 3,
        "podiums": 11,
        "poles": 4,
        "dnfs": 4,
        "points": 76
      },
      {
        "name": "Nigel Mansell",
        "wins": 6,
        "podiums": 7,
        "poles": 8,
        "dnfs": 6,
        "points": 61
      }
    ],
    "total": {
      "wins": 9,
      "podiums": 18,
      "poles": 12,
      "dnfs": 10,
      "points": 137
    }
  },
  "1988": {
    "constructorName": "McLaren-Honda",
    "drivers": [
      {
        "name": "Alain Prost",
        "wins": 7,
        "podiums": 14,
        "poles": 2,
        "dnfs": 2,
        "points": 105
      },
      {
        "name": "Ayrton Senna",
        "wins": 8,
        "podiums": 11,
        "poles": 13,
        "dnfs": 3,
        "points": 94
      }
    ],
    "total": {
      "wins": 15,
      "podiums": 25,
      "poles": 15,
      "dnfs": 5,
      "points": 199
    }
  },
  "1989": {
    "constructorName": "McLaren-Honda",
    "drivers": [
      {
        "name": "Alain Prost",
        "wins": 4,
        "podiums": 11,
        "poles": 2,
        "dnfs": 3,
        "points": 81
      },
      {
        "name": "Ayrton Senna",
        "wins": 6,
        "podiums": 7,
        "poles": 13,
        "dnfs": 8,
        "points": 60
      }
    ],
    "total": {
      "wins": 10,
      "podiums": 18,
      "poles": 15,
      "dnfs": 11,
      "points": 141
    }
  },
  "1990": {
    "constructorName": "McLaren-Honda",
    "drivers": [
      {
        "name": "Ayrton Senna",
        "wins": 6,
        "podiums": 11,
        "poles": 10,
        "dnfs": 5,
        "points": 78
      },
      {
        "name": "Gerhard Berger",
        "wins": 0,
        "podiums": 7,
        "poles": 2,
        "dnfs": 5,
        "points": 43
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 18,
      "poles": 12,
      "dnfs": 10,
      "points": 121
    }
  },
  "1991": {
    "constructorName": "McLaren-Honda",
    "drivers": [
      {
        "name": "Ayrton Senna",
        "wins": 7,
        "podiums": 12,
        "poles": 8,
        "dnfs": 3,
        "points": 96
      },
      {
        "name": "Gerhard Berger",
        "wins": 1,
        "podiums": 6,
        "poles": 2,
        "dnfs": 7,
        "points": 43
      }
    ],
    "total": {
      "wins": 8,
      "podiums": 18,
      "poles": 10,
      "dnfs": 10,
      "points": 139
    }
  },
  "1992": {
    "constructorName": "Williams-Renault",
    "drivers": [
      {
        "name": "Nigel Mansell",
        "wins": 9,
        "podiums": 12,
        "poles": 14,
        "dnfs": 4,
        "points": 108
      },
      {
        "name": "Riccardo Patrese",
        "wins": 1,
        "podiums": 9,
        "poles": 1,
        "dnfs": 6,
        "points": 56
      }
    ],
    "total": {
      "wins": 10,
      "podiums": 21,
      "poles": 15,
      "dnfs": 10,
      "points": 164
    }
  },
  "1993": {
    "constructorName": "Williams-Renault",
    "drivers": [
      {
        "name": "Alain Prost",
        "wins": 7,
        "podiums": 12,
        "poles": 13,
        "dnfs": 2,
        "points": 99
      },
      {
        "name": "Damon Hill",
        "wins": 3,
        "podiums": 10,
        "poles": 2,
        "dnfs": 5,
        "points": 69
      }
    ],
    "total": {
      "wins": 10,
      "podiums": 22,
      "poles": 15,
      "dnfs": 7,
      "points": 168
    }
  },
  "1994": {
    "constructorName": "Williams-Renault",
    "drivers": [
      {
        "name": "Damon Hill",
        "wins": 6,
        "podiums": 11,
        "poles": 2,
        "dnfs": 3,
        "points": 91
      },
      {
        "name": "David Coulthard",
        "wins": 0,
        "podiums": 1,
        "poles": 0,
        "dnfs": 4,
        "points": 14
      },
      {
        "name": "Nigel Mansell",
        "wins": 1,
        "podiums": 1,
        "poles": 1,
        "dnfs": 2,
        "points": 13
      }
    ],
    "total": {
      "wins": 7,
      "podiums": 13,
      "poles": 3,
      "dnfs": 9,
      "points": 118
    }
  },
  "1995": {
    "constructorName": "Benetton-Renault",
    "drivers": [
      {
        "name": "Michael Schumacher",
        "wins": 9,
        "podiums": 11,
        "poles": 4,
        "dnfs": 5,
        "points": 102
      },
      {
        "name": "Johnny Herbert",
        "wins": 2,
        "podiums": 4,
        "poles": 0,
        "dnfs": 4,
        "points": 45
      }
    ],
    "total": {
      "wins": 11,
      "podiums": 15,
      "poles": 4,
      "dnfs": 9,
      "points": 147
    }
  },
  "1996": {
    "constructorName": "Williams-Renault",
    "drivers": [
      {
        "name": "Damon Hill",
        "wins": 8,
        "podiums": 10,
        "poles": 9,
        "dnfs": 4,
        "points": 97
      },
      {
        "name": "Jacques Villeneuve",
        "wins": 4,
        "podiums": 11,
        "poles": 3,
        "dnfs": 4,
        "points": 78
      }
    ],
    "total": {
      "wins": 12,
      "podiums": 21,
      "poles": 12,
      "dnfs": 8,
      "points": 175
    }
  },
  "1997": {
    "constructorName": "Williams-Renault",
    "drivers": [
      {
        "name": "Jacques Villeneuve",
        "wins": 7,
        "podiums": 8,
        "poles": 10,
        "dnfs": 6,
        "points": 81
      },
      {
        "name": "Heinz-Harald Frentzen",
        "wins": 1,
        "podiums": 7,
        "poles": 1,
        "dnfs": 6,
        "points": 42
      }
    ],
    "total": {
      "wins": 8,
      "podiums": 15,
      "poles": 11,
      "dnfs": 12,
      "points": 123
    }
  },
  "1998": {
    "constructorName": "McLaren-Mercedes",
    "drivers": [
      {
        "name": "Mika Häkkinen",
        "wins": 8,
        "podiums": 11,
        "poles": 9,
        "dnfs": 3,
        "points": 100
      },
      {
        "name": "David Coulthard",
        "wins": 1,
        "podiums": 9,
        "poles": 3,
        "dnfs": 4,
        "points": 56
      }
    ],
    "total": {
      "wins": 9,
      "podiums": 20,
      "poles": 12,
      "dnfs": 7,
      "points": 156
    }
  },
  "1999": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Eddie Irvine",
        "wins": 4,
        "podiums": 9,
        "poles": 0,
        "dnfs": 1,
        "points": 74
      },
      {
        "name": "Michael Schumacher",
        "wins": 2,
        "podiums": 6,
        "poles": 3,
        "dnfs": 2,
        "points": 44
      },
      {
        "name": "Mika Salo",
        "wins": 0,
        "podiums": 2,
        "poles": 0,
        "dnfs": 1,
        "points": 10
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 17,
      "poles": 3,
      "dnfs": 4,
      "points": 128
    }
  },
  "2000": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Michael Schumacher",
        "wins": 9,
        "podiums": 12,
        "poles": 9,
        "dnfs": 4,
        "points": 108
      },
      {
        "name": "Rubens Barrichello",
        "wins": 1,
        "podiums": 9,
        "poles": 1,
        "dnfs": 4,
        "points": 62
      }
    ],
    "total": {
      "wins": 10,
      "podiums": 21,
      "poles": 10,
      "dnfs": 8,
      "points": 170
    }
  },
  "2001": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Michael Schumacher",
        "wins": 9,
        "podiums": 14,
        "poles": 11,
        "dnfs": 2,
        "points": 123
      },
      {
        "name": "Rubens Barrichello",
        "wins": 0,
        "podiums": 10,
        "poles": 0,
        "dnfs": 4,
        "points": 56
      }
    ],
    "total": {
      "wins": 9,
      "podiums": 24,
      "poles": 11,
      "dnfs": 6,
      "points": 179
    }
  },
  "2002": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Michael Schumacher",
        "wins": 11,
        "podiums": 17,
        "poles": 7,
        "dnfs": 0,
        "points": 144
      },
      {
        "name": "Rubens Barrichello",
        "wins": 4,
        "podiums": 10,
        "poles": 3,
        "dnfs": 5,
        "points": 77
      }
    ],
    "total": {
      "wins": 15,
      "podiums": 27,
      "poles": 10,
      "dnfs": 5,
      "points": 221
    }
  },
  "2003": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Michael Schumacher",
        "wins": 6,
        "podiums": 8,
        "poles": 5,
        "dnfs": 1,
        "points": 93
      },
      {
        "name": "Rubens Barrichello",
        "wins": 2,
        "podiums": 8,
        "poles": 3,
        "dnfs": 5,
        "points": 65
      }
    ],
    "total": {
      "wins": 8,
      "podiums": 16,
      "poles": 8,
      "dnfs": 6,
      "points": 158
    }
  },
  "2004": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Michael Schumacher",
        "wins": 13,
        "podiums": 15,
        "poles": 8,
        "dnfs": 1,
        "points": 148
      },
      {
        "name": "Rubens Barrichello",
        "wins": 2,
        "podiums": 14,
        "poles": 4,
        "dnfs": 1,
        "points": 114
      }
    ],
    "total": {
      "wins": 15,
      "podiums": 29,
      "poles": 12,
      "dnfs": 2,
      "points": 262
    }
  },
  "2005": {
    "constructorName": "Renault",
    "drivers": [
      {
        "name": "Fernando Alonso",
        "wins": 7,
        "podiums": 15,
        "poles": 6,
        "dnfs": 2,
        "points": 133
      },
      {
        "name": "Giancarlo Fisichella",
        "wins": 1,
        "podiums": 3,
        "poles": 1,
        "dnfs": 6,
        "points": 58
      }
    ],
    "total": {
      "wins": 8,
      "podiums": 18,
      "poles": 7,
      "dnfs": 8,
      "points": 191
    }
  },
  "2006": {
    "constructorName": "Renault",
    "drivers": [
      {
        "name": "Fernando Alonso",
        "wins": 7,
        "podiums": 14,
        "poles": 6,
        "dnfs": 2,
        "points": 134
      },
      {
        "name": "Giancarlo Fisichella",
        "wins": 1,
        "podiums": 5,
        "poles": 1,
        "dnfs": 2,
        "points": 72
      }
    ],
    "total": {
      "wins": 8,
      "podiums": 19,
      "poles": 7,
      "dnfs": 4,
      "points": 206
    }
  },
  "2007": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Kimi Räikkönen",
        "wins": 6,
        "podiums": 12,
        "poles": 3,
        "dnfs": 2,
        "points": 110
      },
      {
        "name": "Felipe Massa",
        "wins": 3,
        "podiums": 10,
        "poles": 6,
        "dnfs": 2,
        "points": 94
      }
    ],
    "total": {
      "wins": 9,
      "podiums": 22,
      "poles": 9,
      "dnfs": 4,
      "points": 204
    }
  },
  "2008": {
    "constructorName": "Ferrari",
    "drivers": [
      {
        "name": "Felipe Massa",
        "wins": 6,
        "podiums": 10,
        "poles": 6,
        "dnfs": 3,
        "points": 97
      },
      {
        "name": "Kimi Räikkönen",
        "wins": 2,
        "podiums": 9,
        "poles": 2,
        "dnfs": 5,
        "points": 75
      }
    ],
    "total": {
      "wins": 8,
      "podiums": 19,
      "poles": 8,
      "dnfs": 8,
      "points": 172
    }
  },
  "2009": {
    "constructorName": "Brawn",
    "drivers": [
      {
        "name": "Jenson Button",
        "wins": 6,
        "podiums": 9,
        "poles": 4,
        "dnfs": 1,
        "points": 95
      },
      {
        "name": "Rubens Barrichello",
        "wins": 2,
        "podiums": 6,
        "poles": 1,
        "dnfs": 1,
        "points": 77
      }
    ],
    "total": {
      "wins": 8,
      "podiums": 15,
      "poles": 5,
      "dnfs": 2,
      "points": 172
    }
  },
  "2010": {
    "constructorName": "Red Bull",
    "drivers": [
      {
        "name": "Sebastian Vettel",
        "wins": 5,
        "podiums": 10,
        "poles": 10,
        "dnfs": 3,
        "points": 256
      },
      {
        "name": "Mark Webber",
        "wins": 4,
        "podiums": 10,
        "poles": 5,
        "dnfs": 2,
        "points": 242
      }
    ],
    "total": {
      "wins": 9,
      "podiums": 20,
      "poles": 15,
      "dnfs": 5,
      "points": 498
    }
  },
  "2011": {
    "constructorName": "Red Bull",
    "drivers": [
      {
        "name": "Sebastian Vettel",
        "wins": 11,
        "podiums": 17,
        "poles": 15,
        "dnfs": 1,
        "points": 392
      },
      {
        "name": "Mark Webber",
        "wins": 1,
        "podiums": 10,
        "poles": 3,
        "dnfs": 1,
        "points": 258
      }
    ],
    "total": {
      "wins": 12,
      "podiums": 27,
      "poles": 18,
      "dnfs": 2,
      "points": 650
    }
  },
  "2012": {
    "constructorName": "Red Bull",
    "drivers": [
      {
        "name": "Sebastian Vettel",
        "wins": 5,
        "podiums": 10,
        "poles": 6,
        "dnfs": 2,
        "points": 281
      },
      {
        "name": "Mark Webber",
        "wins": 2,
        "podiums": 4,
        "poles": 2,
        "dnfs": 3,
        "points": 179
      }
    ],
    "total": {
      "wins": 7,
      "podiums": 14,
      "poles": 8,
      "dnfs": 5,
      "points": 460
    }
  },
  "2013": {
    "constructorName": "Red Bull",
    "drivers": [
      {
        "name": "Sebastian Vettel",
        "wins": 13,
        "podiums": 16,
        "poles": 9,
        "dnfs": 1,
        "points": 397
      },
      {
        "name": "Mark Webber",
        "wins": 0,
        "podiums": 8,
        "poles": 2,
        "dnfs": 4,
        "points": 199
      }
    ],
    "total": {
      "wins": 13,
      "podiums": 24,
      "poles": 11,
      "dnfs": 5,
      "points": 596
    }
  },
  "2014": {
    "constructorName": "Mercedes",
    "drivers": [
      {
        "name": "Lewis Hamilton",
        "wins": 11,
        "podiums": 16,
        "poles": 7,
        "dnfs": 3,
        "points": 384
      },
      {
        "name": "Nico Rosberg",
        "wins": 5,
        "podiums": 15,
        "poles": 11,
        "dnfs": 2,
        "points": 317
      }
    ],
    "total": {
      "wins": 16,
      "podiums": 31,
      "poles": 18,
      "dnfs": 5,
      "points": 701
    }
  },
  "2015": {
    "constructorName": "Mercedes",
    "drivers": [
      {
        "name": "Lewis Hamilton",
        "wins": 10,
        "podiums": 17,
        "poles": 11,
        "dnfs": 1,
        "points": 381
      },
      {
        "name": "Nico Rosberg",
        "wins": 6,
        "podiums": 15,
        "poles": 7,
        "dnfs": 1,
        "points": 322
      }
    ],
    "total": {
      "wins": 16,
      "podiums": 32,
      "poles": 18,
      "dnfs": 2,
      "points": 703
    }
  },
  "2016": {
    "constructorName": "Mercedes",
    "drivers": [
      {
        "name": "Nico Rosberg",
        "wins": 9,
        "podiums": 16,
        "poles": 8,
        "dnfs": 1,
        "points": 385
      },
      {
        "name": "Lewis Hamilton",
        "wins": 10,
        "podiums": 17,
        "poles": 12,
        "dnfs": 2,
        "points": 380
      }
    ],
    "total": {
      "wins": 19,
      "podiums": 33,
      "poles": 20,
      "dnfs": 3,
      "points": 765
    }
  },
  "2017": {
    "constructorName": "Mercedes",
    "drivers": [
      {
        "name": "Lewis Hamilton",
        "wins": 9,
        "podiums": 13,
        "poles": 11,
        "dnfs": 0,
        "points": 363
      },
      {
        "name": "Valtteri Bottas",
        "wins": 3,
        "podiums": 13,
        "poles": 4,
        "dnfs": 1,
        "points": 305
      }
    ],
    "total": {
      "wins": 12,
      "podiums": 26,
      "poles": 15,
      "dnfs": 1,
      "points": 668
    }
  },
  "2018": {
    "constructorName": "Mercedes",
    "drivers": [
      {
        "name": "Lewis Hamilton",
        "wins": 11,
        "podiums": 17,
        "poles": 11,
        "dnfs": 1,
        "points": 408
      },
      {
        "name": "Valtteri Bottas",
        "wins": 0,
        "podiums": 8,
        "poles": 2,
        "dnfs": 2,
        "points": 247
      }
    ],
    "total": {
      "wins": 11,
      "podiums": 25,
      "poles": 13,
      "dnfs": 3,
      "points": 655
    }
  },
  "2019": {
    "constructorName": "Mercedes",
    "drivers": [
      {
        "name": "Lewis Hamilton",
        "wins": 11,
        "podiums": 17,
        "poles": 5,
        "dnfs": 0,
        "points": 413
      },
      {
        "name": "Valtteri Bottas",
        "wins": 4,
        "podiums": 15,
        "poles": 5,
        "dnfs": 2,
        "points": 326
      }
    ],
    "total": {
      "wins": 15,
      "podiums": 32,
      "poles": 10,
      "dnfs": 2,
      "points": 739
    }
  },
  "2020": {
    "constructorName": "Mercedes",
    "drivers": [
      {
        "name": "Lewis Hamilton",
        "wins": 11,
        "podiums": 14,
        "poles": 10,
        "dnfs": 0,
        "points": 347
      },
      {
        "name": "Valtteri Bottas",
        "wins": 2,
        "podiums": 11,
        "poles": 5,
        "dnfs": 1,
        "points": 223
      },
      {
        "name": "George Russell",
        "wins": 0,
        "podiums": 0,
        "poles": 0,
        "dnfs": 0,
        "points": 3
      }
    ],
    "total": {
      "wins": 13,
      "podiums": 25,
      "poles": 15,
      "dnfs": 1,
      "points": 573
    }
  },
  "2021": {
    "constructorName": "Mercedes",
    "drivers": [
      {
        "name": "Lewis Hamilton",
        "wins": 8,
        "podiums": 17,
        "poles": 5,
        "dnfs": 1,
        "points": 387.5
      },
      {
        "name": "Valtteri Bottas",
        "wins": 1,
        "podiums": 11,
        "poles": 4,
        "dnfs": 4,
        "points": 226
      }
    ],
    "total": {
      "wins": 9,
      "podiums": 28,
      "poles": 9,
      "dnfs": 5,
      "points": 613.5
    }
  },
  "2022": {
    "constructorName": "Red Bull",
    "drivers": [
      {
        "name": "Max Verstappen",
        "wins": 15,
        "podiums": 17,
        "poles": 7,
        "dnfs": 2,
        "points": 454
      },
      {
        "name": "Sergio Pérez",
        "wins": 2,
        "podiums": 11,
        "poles": 1,
        "dnfs": 3,
        "points": 305
      }
    ],
    "total": {
      "wins": 17,
      "podiums": 28,
      "poles": 8,
      "dnfs": 5,
      "points": 759
    }
  },
  "2023": {
    "constructorName": "Red Bull",
    "drivers": [
      {
        "name": "Max Verstappen",
        "wins": 19,
        "podiums": 21,
        "poles": 12,
        "dnfs": 0,
        "points": 575
      },
      {
        "name": "Sergio Pérez",
        "wins": 2,
        "podiums": 9,
        "poles": 2,
        "dnfs": 2,
        "points": 285
      }
    ],
    "total": {
      "wins": 21,
      "podiums": 30,
      "poles": 14,
      "dnfs": 2,
      "points": 860
    }
  },
  "2024": {
    "constructorName": "McLaren",
    "drivers": [
      {
        "name": "Lando Norris",
        "wins": 4,
        "podiums": 13,
        "poles": 8,
        "dnfs": 0,
        "points": 374
      },
      {
        "name": "Oscar Piastri",
        "wins": 2,
        "podiums": 8,
        "poles": 0,
        "dnfs": 0,
        "points": 292
      }
    ],
    "total": {
      "wins": 6,
      "podiums": 21,
      "poles": 8,
      "dnfs": 0,
      "points": 666
    }
  },
  "2025": {
    "constructorName": "McLaren",
    "drivers": [
      {
        "name": "Lando Norris",
        "wins": 7,
        "podiums": 18,
        "poles": 7,
        "dnfs": 3,
        "points": 423
      },
      {
        "name": "Oscar Piastri",
        "wins": 7,
        "podiums": 16,
        "poles": 5,
        "dnfs": 2,
        "points": 410
      }
    ],
    "total": {
      "wins": 14,
      "podiums": 34,
      "poles": 12,
      "dnfs": 5,
      "points": 833
    }
  }
};
